name: yleaf
channels:
  - anaconda
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - atk-1.0=2.36.0=ha1a6a79_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2022.6.15=py37h06a4308_0
  - curl=7.84.0=h5eee18b_0
  - expat=2.4.4=h295c915_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.1=h6c09931_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.8=h433bba3_0
  - glib=2.69.1=h4ff587b_1
  - gobject-introspection=1.72.0=py37hbb6d50b_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h3cd0ef9_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hd55b92a_0
  - icu=58.2=he6710b0_3
  - jpeg=9e=h7f8727e_0
  - k8=0.2.5=h9a82719_1
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.54.4=h19fe530_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h2818925_1
  - libtool=2.4.6=h295c915_1008
  - libuuid=1.0.3=h7f8727e_2
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - minimap2=2.17=h5bf99c6_4
  - ncurses=6.3=h5eee18b_3
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - openssl=1.1.1q=h7f8727e_0
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h295c915_0
  - pip=22.1.2=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - samtools=1.6=hb116620_7
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - numpy==1.18.5
    - pandas==1.1.5
    - python-dateutil==2.8.2
    - graphviz==0.19.2
    - pytz==2022.2.1
    - setuptools==41.2.0
    - six==1.16.0
